apiVersion: batch/v1
kind: Job
metadata:
    name: {{ template "eventgrid-subscriber.name" . }}
    app: {{ template "eventgrid-subscriber.name" . }}
    chart: {{ template "eventgrid-subscriber.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RESOURCE_GROUP
          value: {{ .Values.azureValues.RESOURCE_GROUP | quote }}
        - name: STORAGE_ACCOUNT
          value: {{ .Values.azureValues.STORAGE_ACCOUNT | quote }}
        - name: EVENTGRID_SUBSCRIPTION_NAME
          value: {{ .Values.azureValues.EVENTGRID_SUBSCRIPTION_NAME | quote }}
        - name: WEBHOOK_URL
          value: {{ .Values.azureValues.WEBHOOK_URL | quote }}
        - name: AZ_SUBSCRIPTION_ID
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.azureSecret }}
              key: AZ_SUBSCRIPTION_ID
        - name: AZ_TENANT_ID
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.azureSecret }}
              key: AZ_TENANT_ID
        - name: AZ_CLIENT_ID
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.azureSecret }}
              key: AZ_CLIENT_ID
        - name: "AZ_CLIENT_SECRET"
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.azureSecret }}
              key: AZ_CLIENT_SECRET
      restartPolicy: {{ .Values.restartPolicy }}
