# This shows a secret as a pre-install hook.
# A pre-install hook is run before the rest of the chart is loaded.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eventgrid-subscriber.name" . }}-secret
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  AZ_SUBSCRIPTION_ID: {{ .Values.azureSecret.AZ_SUBSCRIPTION_ID | b64enc  }}
  AZ_TENANT_ID: {{ .Values.azureSecret.AZ_TENANT_ID | b64enc  }}
  AZ_CLIENT_ID: {{ .Values.azureSecret.AZ_CLIENT_ID | b64enc  }}
  AZ_CLIENT_SECRET: {{ .Values.azureSecret.AZ_CLIENT_SECRET | b64enc  }}

