
[[constraint]]
  name = "github.com/Azure/brigade"
  revision = "2d50a318013b101611c0c466d8078d3f84aae568"

[[constraint]]
  name = "k8s.io/api"
  revision = "6c6dac0277229b9e9578c5ca3f74a4345d35cdc2"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "019ae5ada31de202164b118aee88ee2d14075c31"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
