[[constraint]]
  name = "github.com/azure/brigade"

[[constraint]]
  name = "github.com/gin-gonic/gin"

# Azure EventGrid dependencies
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "^12.4.0-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "^9.6.0"