replicaCount: 1

rbac:
  enabled: true

image:
  repository: radumatei/brigade-eventgrid-gateway
  tag: v0.1.6
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 8080
  externalPort: 80


# for Azure EventGrid you must have TLS ingress
# more information here - https://docs.microsoft.com/en-us/azure/event-grid/security-authentication
ingress:
  enabled: true
# by default, this chart uses TLS the annotations for kube-lego and nginx-ingress
# if you have a different ingress controller, make sure to change them in ingress.yaml

  # annotations:
  #   kubernetes.io/tls-acme: "true"
  #   kubernetes.io/ingress.class: "nginx"
  host: <your-HTTPS-endpoint>
